// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  const fibo = [1, 2];
  let sum;
  while ((sum = fibo[fibo.length - 1] + fibo[fibo.length - 2]) <= n) {
    fibo.push(sum)
  }
  return fibo
    .filter((data) => data % 2 === 0)
    .reduce((acc, cur) => acc + cur)
}